// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: co.aktivi.actor.getProfileView
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetProfileView<'a> {
    #[serde(borrow)]
    pub actor: jacquard_common::types::ident::AtIdentifier<'a>,
}

pub mod get_profile_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Actor;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Actor = Unset;
    }
    ///State transition - sets the `actor` field to Set
    pub struct SetActor<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetActor<S> {}
    impl<S: State> State for SetActor<S> {
        type Actor = Set<members::actor>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `actor` field
        pub struct actor(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetProfileViewBuilder<'a, S: get_profile_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::ident::AtIdentifier<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetProfileView<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetProfileViewBuilder<'a, get_profile_view_state::Empty> {
        GetProfileViewBuilder::new()
    }
}

impl<'a> GetProfileViewBuilder<'a, get_profile_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetProfileViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetProfileViewBuilder<'a, S>
where
    S: get_profile_view_state::State,
    S::Actor: get_profile_view_state::IsUnset,
{
    /// Set the `actor` field (required)
    pub fn actor(
        mut self,
        value: impl Into<jacquard_common::types::ident::AtIdentifier<'a>>,
    ) -> GetProfileViewBuilder<'a, get_profile_view_state::SetActor<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetProfileViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetProfileViewBuilder<'a, S>
where
    S: get_profile_view_state::State,
    S::Actor: get_profile_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetProfileView<'a> {
        GetProfileView {
            actor: self.__unsafe_private_named.0.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetProfileViewOutput<'a> {
    #[serde(borrow)]
    pub profile: crate::co_aktivi::actor::ProfileView<'a>,
}

/// Response type for
///co.aktivi.actor.getProfileView
pub struct GetProfileViewResponse;
impl jacquard_common::xrpc::XrpcResp for GetProfileViewResponse {
    const NSID: &'static str = "co.aktivi.actor.getProfileView";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetProfileViewOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetProfileView<'a> {
    const NSID: &'static str = "co.aktivi.actor.getProfileView";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetProfileViewResponse;
}

/// Endpoint type for
///co.aktivi.actor.getProfileView
pub struct GetProfileViewRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetProfileViewRequest {
    const PATH: &'static str = "/xrpc/co.aktivi.actor.getProfileView";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetProfileView<'de>;
    type Response = GetProfileViewResponse;
}