// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: co.aktivi.meta.ootb
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// Out-of-box experience and app metadata.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Ootb<'a> {
    /// Version string of the last update modal the user saw.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub last_seen_update_modal: std::option::Option<jacquard_common::CowStr<'a>>,
    /// Whether the user has completed onboarding.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub ootb_complete: std::option::Option<bool>,
}

pub mod ootb_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct OotbBuilder<'a, S: ootb_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<bool>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Ootb<'a> {
    /// Create a new builder for this type
    pub fn new() -> OotbBuilder<'a, ootb_state::Empty> {
        OotbBuilder::new()
    }
}

impl<'a> OotbBuilder<'a, ootb_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        OotbBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: ootb_state::State> OotbBuilder<'a, S> {
    /// Set the `lastSeenUpdateModal` field (optional)
    pub fn last_seen_update_modal(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `lastSeenUpdateModal` field to an Option value (optional)
    pub fn maybe_last_seen_update_modal(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: ootb_state::State> OotbBuilder<'a, S> {
    /// Set the `ootbComplete` field (optional)
    pub fn ootb_complete(mut self, value: impl Into<Option<bool>>) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `ootbComplete` field to an Option value (optional)
    pub fn maybe_ootb_complete(mut self, value: Option<bool>) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S> OotbBuilder<'a, S>
where
    S: ootb_state::State,
{
    /// Build the final struct
    pub fn build(self) -> Ootb<'a> {
        Ootb {
            last_seen_update_modal: self.__unsafe_private_named.0,
            ootb_complete: self.__unsafe_private_named.1,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Ootb<'a> {
        Ootb {
            last_seen_update_modal: self.__unsafe_private_named.0,
            ootb_complete: self.__unsafe_private_named.1,
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Ootb<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, OotbRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct OotbGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Ootb<'a>,
}

impl From<OotbGetRecordOutput<'_>> for Ootb<'_> {
    fn from(output: OotbGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Ootb<'_> {
    const NSID: &'static str = "co.aktivi.meta.ootb";
    type Record = OotbRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct OotbRecord;
impl jacquard_common::xrpc::XrpcResp for OotbRecord {
    const NSID: &'static str = "co.aktivi.meta.ootb";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = OotbGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for OotbRecord {
    const NSID: &'static str = "co.aktivi.meta.ootb";
    type Record = OotbRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Ootb<'a> {
    fn nsid() -> &'static str {
        "co.aktivi.meta.ootb"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_co_aktivi_meta_ootb()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_co_aktivi_meta_ootb() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("co.aktivi.meta.ootb"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "Out-of-box experience and app metadata.",
                        ),
                    ),
                    key: Some(::jacquard_common::CowStr::new_static("literal:self")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: None,
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "lastSeenUpdateModal",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Version string of the last update modal the user saw.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "ootbComplete",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Boolean(::jacquard_lexicon::lexicon::LexBoolean {
                                    description: None,
                                    default: None,
                                    r#const: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}