/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserHandleRouteImport } from './routes/user.$handle'
import { Route as OauthPreRouteImport } from './routes/oauth.pre'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as LegalTosRouteImport } from './routes/legal.tos'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal.privacy-policy'
import { Route as LegalContentGuidelinesRouteImport } from './routes/legal.content-guidelines'
import { Route as EventsCreateRouteImport } from './routes/events.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHandleRoute = UserHandleRouteImport.update({
  id: '/user/$handle',
  path: '/user/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthPreRoute = OauthPreRouteImport.update({
  id: '/oauth/pre',
  path: '/oauth/pre',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTosRoute = LegalTosRouteImport.update({
  id: '/legal/tos',
  path: '/legal/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalContentGuidelinesRoute = LegalContentGuidelinesRouteImport.update({
  id: '/legal/content-guidelines',
  path: '/legal/content-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/events/create': typeof EventsCreateRoute
  '/legal/content-guidelines': typeof LegalContentGuidelinesRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/pre': typeof OauthPreRoute
  '/user/$handle': typeof UserHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/events/create': typeof EventsCreateRoute
  '/legal/content-guidelines': typeof LegalContentGuidelinesRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/pre': typeof OauthPreRoute
  '/user/$handle': typeof UserHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/events/create': typeof EventsCreateRoute
  '/legal/content-guidelines': typeof LegalContentGuidelinesRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/tos': typeof LegalTosRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/oauth/pre': typeof OauthPreRoute
  '/user/$handle': typeof UserHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/login'
    | '/events/create'
    | '/legal/content-guidelines'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/oauth/callback'
    | '/oauth/pre'
    | '/user/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/login'
    | '/events/create'
    | '/legal/content-guidelines'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/oauth/callback'
    | '/oauth/pre'
    | '/user/$handle'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/login'
    | '/events/create'
    | '/legal/content-guidelines'
    | '/legal/privacy-policy'
    | '/legal/tos'
    | '/oauth/callback'
    | '/oauth/pre'
    | '/user/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LegalContentGuidelinesRoute: typeof LegalContentGuidelinesRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalTosRoute: typeof LegalTosRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OauthPreRoute: typeof OauthPreRoute
  UserHandleRoute: typeof UserHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$handle': {
      id: '/user/$handle'
      path: '/user/$handle'
      fullPath: '/user/$handle'
      preLoaderRoute: typeof UserHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/pre': {
      id: '/oauth/pre'
      path: '/oauth/pre'
      fullPath: '/oauth/pre'
      preLoaderRoute: typeof OauthPreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/tos': {
      id: '/legal/tos'
      path: '/legal/tos'
      fullPath: '/legal/tos'
      preLoaderRoute: typeof LegalTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/content-guidelines': {
      id: '/legal/content-guidelines'
      path: '/legal/content-guidelines'
      fullPath: '/legal/content-guidelines'
      preLoaderRoute: typeof LegalContentGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsCreateRoute: typeof EventsCreateRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsCreateRoute: EventsCreateRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  LegalContentGuidelinesRoute: LegalContentGuidelinesRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalTosRoute: LegalTosRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OauthPreRoute: OauthPreRoute,
  UserHandleRoute: UserHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
