// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: co.aktivi.event.getEventView
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetEventView<'a> {
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
}

pub mod get_event_view_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetUri<S> {}
    impl<S: State> State for SetUri<S> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetEventViewBuilder<'a, S: get_event_view_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::string::AtUri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetEventView<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetEventViewBuilder<'a, get_event_view_state::Empty> {
        GetEventViewBuilder::new()
    }
}

impl<'a> GetEventViewBuilder<'a, get_event_view_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetEventViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None,),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetEventViewBuilder<'a, S>
where
    S: get_event_view_state::State,
    S::Uri: get_event_view_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<jacquard_common::types::string::AtUri<'a>>,
    ) -> GetEventViewBuilder<'a, get_event_view_state::SetUri<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetEventViewBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetEventViewBuilder<'a, S>
where
    S: get_event_view_state::State,
    S::Uri: get_event_view_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetEventView<'a> {
        GetEventView {
            uri: self.__unsafe_private_named.0.unwrap(),
        }
    }
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetEventViewOutput<'a> {
    #[serde(borrow)]
    pub event: crate::co_aktivi::event::EventViewDetailed<'a>,
}

/// Response type for
///co.aktivi.event.getEventView
pub struct GetEventViewResponse;
impl jacquard_common::xrpc::XrpcResp for GetEventViewResponse {
    const NSID: &'static str = "co.aktivi.event.getEventView";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetEventViewOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetEventView<'a> {
    const NSID: &'static str = "co.aktivi.event.getEventView";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetEventViewResponse;
}

/// Endpoint type for
///co.aktivi.event.getEventView
pub struct GetEventViewRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetEventViewRequest {
    const PATH: &'static str = "/xrpc/co.aktivi.event.getEventView";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetEventView<'de>;
    type Response = GetEventViewResponse;
}