// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.example.createRecord
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct CreateRecord<'a> {
    #[serde(borrow)]
    pub text: jacquard_common::CowStr<'a>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct CreateRecordOutput<'a> {
    #[serde(borrow)]
    pub cid: jacquard_common::types::string::Cid<'a>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
}

/// Response type for
///com.example.createRecord
pub struct CreateRecordResponse;
impl jacquard_common::xrpc::XrpcResp for CreateRecordResponse {
    const NSID: &'static str = "com.example.createRecord";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CreateRecordOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for CreateRecord<'a> {
    const NSID: &'static str = "com.example.createRecord";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = CreateRecordResponse;
}

/// Endpoint type for
///com.example.createRecord
pub struct CreateRecordRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateRecordRequest {
    const PATH: &'static str = "/xrpc/com.example.createRecord";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = CreateRecord<'de>;
    type Response = CreateRecordResponse;
}