// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.example.getStatus
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetStatus;
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct GetStatusOutput<'a> {
    #[serde(borrow)]
    pub status: jacquard_common::CowStr<'a>,
    #[serde(borrow)]
    pub version: jacquard_common::CowStr<'a>,
}

/// Response type for
///com.example.getStatus
pub struct GetStatusResponse;
impl jacquard_common::xrpc::XrpcResp for GetStatusResponse {
    const NSID: &'static str = "com.example.getStatus";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetStatusOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for GetStatus {
    const NSID: &'static str = "com.example.getStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetStatusResponse;
}

/// Endpoint type for
///com.example.getStatus
pub struct GetStatusRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetStatusRequest {
    const PATH: &'static str = "/xrpc/com.example.getStatus";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetStatus;
    type Response = GetStatusResponse;
}